-- Migration: Add pgvector support for vector embeddings
-- Date: 2025-01-27
-- Description: Adds pgvector extension and embedding column to modern_images table

-- Step 1: Enable pgvector extension (if not already enabled by init script)
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 2: Add embedding column to modern_images table (768 dimensions for ViT-L/14)
ALTER TABLE modern_images
ADD COLUMN IF NOT EXISTS embedding vector(768);

-- Step 3: Create HNSW index for fast cosine similarity search
-- This index will significantly speed up vector similarity queries
CREATE INDEX IF NOT EXISTS modern_images_embedding_idx
ON modern_images
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- Index parameters explained:
-- m = 16: Number of connections per layer (default, good balance)
-- ef_construction = 64: Size of dynamic candidate list for index construction
-- vector_cosine_ops: Use cosine distance for similarity (range 0-2, where 0=identical)

-- Step 4: Add embedding_model column to track which model generated the embedding
ALTER TABLE modern_images
ADD COLUMN IF NOT EXISTS embedding_model VARCHAR(100) DEFAULT 'ViT-L-14';

-- Step 5: Create index on embedding_model for filtering
CREATE INDEX IF NOT EXISTS modern_images_embedding_model_idx
ON modern_images(embedding_model);

-- Step 6: Update embedding_version for new pgvector embeddings
-- Note: Keep existing vector_id for ChromaDB compatibility during migration
COMMENT ON COLUMN modern_images.embedding IS 'Image embedding vector (768-dim) generated by OpenCLIP ViT-L/14';
COMMENT ON COLUMN modern_images.vector_id IS 'Legacy ChromaDB vector ID (for backward compatibility)';
COMMENT ON COLUMN modern_images.embedding_model IS 'Model used to generate embedding (e.g., ViT-L-14, ViT-H-14)';

-- Verification queries (run after migration):
-- SELECT COUNT(*) FROM modern_images WHERE embedding IS NOT NULL;
-- SELECT pg_size_pretty(pg_relation_size('modern_images_embedding_idx'));
-- SELECT * FROM pg_extension WHERE extname = 'vector';
