-- Migration: Add pgvector support for face embeddings
-- Date: 2025-03-17
-- Description: Adds pgvector column and index for faces table

-- Ensure pgvector extension is enabled
CREATE EXTENSION IF NOT EXISTS vector;

-- Add 512-dimension embedding column for FaceNet embeddings
ALTER TABLE faces
ADD COLUMN IF NOT EXISTS embedding vector(512);

-- Create HNSW index for efficient similarity search on face embeddings
CREATE INDEX IF NOT EXISTS faces_embedding_idx
ON faces
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

COMMENT ON COLUMN faces.embedding IS 'Face embedding vector (512-dim) generated by FaceNet512';
